# Generated by Django 3.2.8 on 2021-12-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
