# Generated by Django 3.2.8 on 2021-12-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_studentscore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='score',
            field=models.IntegerField(),
        ),
    ]
