# Generated by Django 3.2.8 on 2021-12-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_studentscore_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamUnchecked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('question_answer', models.CharField(default='None', max_length=1000)),
            ],
        ),
    ]
