# Generated by Django 3.2.8 on 2021-12-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_alter_examunchecked_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examunchecked',
            name='exam_type',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
