# Generated by Django 3.2.8 on 2021-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_examunchecked_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamChecked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('exam_type', models.CharField(default='None', max_length=50)),
                ('question_answer_marks', models.JSONField(verbose_name={})),
            ],
        ),
    ]
