# Generated by Django 3.2.8 on 2021-11-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211115_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), (models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.studenttype'), models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.studenttype'))], default=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.studenttype'), max_length=255),
        ),
    ]
