# Generated by Django 3.2.8 on 2021-11-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20211115_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studenttype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.studenttype'),
        ),
    ]
