# Generated by Django 3.2.8 on 2021-11-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_studenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.studenttype'),
        ),
    ]
